### ISSUE TITLE
Question: ROS version and Python version

### ISSUE THREAD

**Issue by Elfits** [kevinchan04/Skeleton-based-action-recognition#6]
Impressive work!
I want to know which ROS did you use? Melodic?
If so, how did you integrate ROS with python2 with other projects(maybe yolo and openpose) with python3?

Thanks!!

**Comment by kevinchan04** [comment]
> Impressive work!
> I want to know which ROS did you use? Melodic?
> If so, how did you integrate ROS with python2 with other projects(maybe yolo and openpose) with python3?
> 
> Thanks!!

Yes, this project uses ROS Melodic. In ROS environment, you can select python interpreter to using python3 in .py file, Melodic also supports python3. You can refer to the [act_talker](https://github.com/kevinchan04/Skeleton-based-action-recognition/blob/master/src/Modules/act_talker.py) for how to use python in ROS. [talker](https://github.com/kevinchan04/Skeleton-based-action-recognition/blob/master/scripts/talker.py) likes the main function in thie project, it shows how to integrate ROS and Yolo, Openpose. All data from different modules communicate with queue.
